project:
  type: manuscript
  output-dir: docs
  render: 
    - index.qmd

manuscript:
  code-links: repo

execute:
  freeze: auto

format:
  html:
    default: true
    toc: true
    theme: darkly
    include-before-body:
      - text: "This is an in-progress working draft. Please do not cite, quote, or circulate without the authors' written permission."
  apaquarto-pdf:
    nocorrespondence: true
    donotrepeattitle: true
    draftfirst: true
    keep-tex: true
    filters:
      - abstract-section
  apaquarto-docx:
    nocorrespondence: true
    donotrepeattitle: true

format-links: [apaquarto-pdf]
